Repository TEAM-TAB-SPACE/tabspace-front, pull requests merged in 2023-03, with the labels that each got.

#3 [feature] 로그인 로직 중간 머지를 위한 풀리퀘스트
  .env
  components/layout/BaseLayout.tsx
  components/layout/Header.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/api/axios.js
  pages/index.tsx
  pages/login.tsx
  pages/oauth/callback/kakao.ts
  pages/register.tsx
  public/assets/kakaotalk.png
  public/assets/logo.png
  yarn.lock
Labels: feat

#4 [feature] 메인 페이지 메인 배너, 코스 설명 섹션 구현
  pages/index.tsx
  public/images/img1.jpg
  public/images/img2.jpg
  public/images/profile1.jpeg
  public/images/profile2.jpeg
  public/images/profile3.jpeg
  public/images/profile4.jpeg
  yarn.lock
Labels: feat

#5 [feature] 강의 수강장 UI 구현
  components/comment/Comment.tsx
  components/comment/CommentForm.tsx
  components/comment/ReplyButton.tsx
  components/lecture/LecturePlayer.tsx
  components/lecture/LecturePlaylist.tsx
  components/lecture/LectureQnA.tsx
  components/userBadge/IndicatorIcon.tsx
  components/userBadge/UserBadge.tsx
  components/userBadge/UserBadgeIndicator.tsx
  components/userBadge/UserBadgeText.tsx
  components/userBadge/userBadge.ts
  pages/Lecture.tsx
  styles/layout.module.scss
Labels: feat

#7 [feature] 환경변수 개발모드 분리
  .env.development
  .env.production
  config/config.common.ts
  config/config.development.ts
  config/config.export.ts
  config/config.production.ts
  package-lock.json
  package.json
  pages/api/axios.js
  yarn.lock
Labels: feat

#8 [feature] 수강장 강의 영상 재생기능 구현
  components/common/Spin.tsx
  components/lecture/LectureContent.tsx
  components/lecture/LecturePlayer.tsx
  components/lecture/LecturePlaylist.tsx
  hooks/usePlaylist.ts
  mocks/data/lectureroomsData.ts
  mocks/handler.ts
  package-lock.json
  package.json
  pages/Lecture.tsx
  pages/_app.tsx
  pages/api/axios.js
  pages/api/hello.ts
  pages/api/lecture.ts
  store/lecture.ts
  yarn.lock
Labels: feat

#9 [feature] 회원가입기능 구현 완료
  .env
  .env.development
  .env.production
  components/comment/Comment.tsx
  components/comment/CommentForm.tsx
  components/comment/ReplyButton.tsx
  components/common/Spin.tsx
  components/layout/BaseLayout.tsx
  components/layout/Header.tsx
  components/lecture/LectureContent.tsx
  components/lecture/LecturePlayer.tsx
  components/lecture/LecturePlaylist.tsx
  components/lecture/LectureQnA.tsx
  components/userBadge/IndicatorIcon.tsx
  components/userBadge/UserBadge.tsx
  components/userBadge/UserBadgeIndicator.tsx
  components/userBadge/UserBadgeText.tsx
  components/userBadge/userBadge.ts
  config/config.common.ts
  config/config.development.ts
  config/config.export.ts
  config/config.production.ts
  hooks/usePlaylist.ts
  mocks/data/lectureroomsData.ts
  mocks/handler.ts
  next.config.js
  package-lock.json
  package.json
  pages/Lecture.tsx
  pages/_app.tsx
  pages/api/axios.js
  pages/api/hello.ts
  pages/api/lecture.ts
  pages/index.tsx
  pages/login.tsx
  pages/oauth/callback/kakao.js
  pages/register.tsx
  public/assets/kakaotalk.png
  public/assets/logo.png
  public/images/img1.jpg
  public/images/img2.jpg
  public/images/profile1.jpeg
  public/images/profile2.jpeg
  public/images/profile3.jpeg
  public/images/profile4.jpeg
  store/auth.js
  store/lecture.ts
  styles/layout.module.scss
  styles/variables.module.scss
  yarn.lock
Labels: feat

#10 [feature] 강의 수강장 페이지 구현
  .env
  components/comment/Comment.tsx
  components/comment/CommentForm.tsx
  components/common/Spin.tsx
  components/lecture/LectureContent.tsx
  components/lecture/LecturePlaylist.tsx
  components/lecture/LectureQnA.tsx
  components/lecture/LectureTabs.tsx
  components/userBadge/UserBadge.tsx
  components/userBadge/UserBadgeIndicator.tsx
  components/userBadge/userBadge.ts
  hooks/useMediaQueryState.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/api/axios.js
  pages/lecture.tsx
  pages/oauth/callback/kakao.js
  pages/oauth/callback/kakao.ts
  pages/register.tsx
  store/auth.js
  store/lecture.ts
  styles/variables.module.scss
  yarn.lock
Labels: feat

#12 [feature] 대시보드 페이지 구현
  components/common/ProgressWithBackground.tsx
  components/common/SpinCircle.tsx
  components/dashboard/DashboardGreeting.tsx
  components/dashboard/DashboardItem.tsx
  components/dashboard/DashboardLatest.tsx
  components/dashboard/DashboardLayout.tsx
  components/dashboard/dashboardToday/DashboardToday.tsx
  components/dashboard/dashboardToday/GoLearnButton.tsx
  components/lecture/LectureContent.tsx
  components/lecture/LecturePlayer.tsx
  components/lecture/LecturePlaylist.tsx
  mocks/data/todayLecturesData.ts
  package-lock.json
  package.json
  pages/dashboard.tsx
  pages/lecture/[videoId].tsx
  store/lecture.ts
  styles/globals.css
  styles/variables.module.scss
  yarn.lock
Labels: feat

#14 [feature] 대시보드 페이지 구현
  components/comment/Comments.tsx
  components/common/ProgressWithBackground.tsx
  components/dashboard/DashboardAttendance.tsx
  components/dashboard/DashboardItem.tsx
  components/dashboard/DashboardLatest.tsx
  components/dashboard/DashboardLayout.tsx
  components/dashboard/dashboardGrowth/DashboardGrowth.tsx
  components/dashboard/dashboardGrowth/GrowthChart.jsx
  components/dashboard/dashboardMission/DashboardMission.tsx
  components/dashboard/dashboardMission/DashboardMissionSubmit.tsx
  components/dashboard/dashboardMission/MissionList.tsx
  components/dashboard/dashboardMission/MissionListItem.tsx
  components/dashboard/dashboardMission/MissionPopoverContent.tsx
  components/dashboard/dashboardMission/MissionSelect.tsx
  components/dashboard/dashboardMission/MissionUpload.tsx
  components/dashboard/dashboardToday/DashboardToday.tsx
  components/dashboard/dashboardToday/GoLearnButton.tsx
  components/lecture/LectureContent.tsx
  components/lecture/LecturePlaylist.tsx
  components/lecture/LectureQnA.tsx
  config/config.export.ts
  hooks/useAttendance.ts
  hooks/useFetch.ts
  hooks/useMessage.ts
  hooks/useMission.ts
  hooks/usePlaylist.ts
  mocks/commentHandler.ts
  mocks/dashboardMissionHandler.ts
  mocks/data/Comments.ts
  mocks/data/Missions.ts
  mocks/data/growthData.ts
  mocks/data/todayLecturesData.ts
  mocks/handler.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/api/axios.js
  pages/api/axios.ts
  pages/api/dashboard.ts
  pages/api/lecture.ts
  pages/dashboard.tsx
  pages/lecture/[videoId].tsx
  store/comment.ts
  store/dashboard.ts
  store/lecture.ts
  styles/text.module.scss
  styles/variables.module.scss
  utils/time.ts
  yarn.lock
Labels: feat

#16 [feature & fix] 로그인 사용자 정보 저장, 수강장 플레이리스트 렌더링 에러 수정
  components/lecture/LecturePlaylist.tsx
  components/lecture/LectureQnA.tsx
  hooks/useFetch.ts
  mocks/commentHandler.ts
  mocks/handler.ts
  pages/api/axios.ts
  pages/oauth/callback/kakao.js
  store/lecture.ts
Labels: bug, feat

#17 [feature] 메인 랜딩페이지 구현
  components/layout/ FixedSection.jsx
  components/layout/BaseLayout.tsx
  components/layout/Carousel.jsx
  components/layout/Course.jsx
  components/layout/Footer.jsx
  components/layout/Slider.jsx
  package-lock.json
  package.json
  pages/index.tsx
  public/images/Logo1.jpg
  public/images/Logo2.jpg
  public/images/Logo3.jpg
  public/images/Logo4.jpg
  public/images/Logo5.jpg
  public/images/Logo6.jpg
  public/images/btn-left.jpg
  public/images/btn-right.jpg
  public/images/footer1.jpg
  public/images/footer2.jpg
  public/images/footer3.jpg
  public/images/footer4.jpg
  public/images/profile.jpeg
  public/images/profile1.jpeg
  public/images/profile2.jpeg
  public/images/profile3.jpeg
  public/images/profile4.jpeg
  yarn.lock
Labels: feat

#19 [feature] 로그아웃 기능 구현
  components/layout/Header.tsx
  pages/_app.tsx
  pages/api/axios.ts
  pages/login.tsx
  pages/oauth/callback/kakao.js
  store/auth.js
Labels: feat

#20 [feature] 수강장, 대시보드 기능 구현
  components/dashboard/DashboardLatest.tsx
  components/dashboard/DashboardLayout.tsx
  components/layout/Carousel.jsx
  components/layout/Course.jsx
  components/layout/FixedSection.jsx
  components/layout/Footer.jsx
  components/layout/Header.tsx
  components/layout/Slider.jsx
  components/lecture/LectureContent.tsx
  components/lecture/LecturePlayer.tsx
  hooks/useVideoState.ts
  mocks/handler/lecture/lecture.ts
  pages/_app.tsx
  pages/api/lecture.ts
  pages/index.tsx
  pages/lecture/[videoId].tsx
  pages/login.tsx
  pages/register.tsx
  store/auth.js
  tsconfig.json
  utils/localStorage.js
Labels: feat

#22 [fix] v1.0.0 빌드 에러 수정
  .eslintrc.json
  package.json
Labels: bug

#23 [fix] v1.0.0 빌드 경고 수정
  components/comment/CommentForm.tsx
  components/dashboard/dashboardMission/DashboardMission.tsx
  components/dashboard/dashboardMission/MissionUpload.tsx
  components/layout/Carousel.jsx
  components/layout/Slider.jsx
  components/lecture/LecturePlayer.tsx
  components/lecture/LectureQnA.tsx
  hooks/useAuth.ts
  mocks/handler/auth.ts
  pages/api/auth.ts
  pages/api/axios.ts
Labels: feat

#25 [feature] 메인 랜딩페이지 이미지 변경
  components/layout/Slider.jsx
  pages/index.tsx
  public/images/Logo1.jpg
  public/images/Logo2.jpg
  public/images/Logo3.jpg
  public/images/Logo4.jpg
  public/images/Logo5.jpg
  public/images/Logo6.jpg
  public/images/img2.jpg
Labels: feat

#26 [feature] 랜딩페이지 사전 신청 기능 추가
  components/layout/FixedSection.jsx
Labels: feat

#27 [feature] 강의평가, 알림 조회 기능 추가
  components/comment/CommentForm.tsx
  components/comment/Comments.tsx
  components/comment/ReplyForm.tsx
  components/dashboard/DashboardGreeting.tsx
  components/dashboard/DashboardItemNoData.tsx
  components/dashboard/DashboardLatest.tsx
  components/dashboard/DashboardLayout.tsx
  components/dashboard/dashboardMission/MissionUpload.tsx
  components/dashboard/dashboardToday/DashboardToday.tsx
  components/layout/BaseLayout.tsx
  components/layout/Carousel.jsx
  components/layout/Course.jsx
  components/layout/FixedSection.jsx
  components/layout/Footer.jsx
  components/layout/Header.tsx
  components/layout/Slider.jsx
  components/layout/header/AlarmButton.tsx
  components/layout/header/AlarmPopoverContent.tsx
  components/layout/header/Header.tsx
  components/layout/header/LoginContent.tsx
  components/layout/header/MobileDrawer.tsx
  components/lecture/LecturePlayer.tsx
  components/lecture/LecturePlaylist.tsx
  components/lecture/LectureQnA.tsx
  hooks/useFetch.ts
  hooks/usePlaylist.ts
  hooks/useVideoState.ts
  mocks/handler/dashboard/dashboard.ts
  mocks/handler/dashboard/mission.ts
  mocks/handler/handler.ts
  pages/404.tsx
  pages/_app.tsx
  pages/api/auth.ts
  pages/api/axios.ts
  pages/api/dashboard.ts
  pages/api/other.ts
  pages/dashboard.tsx
  pages/index.tsx
  pages/lecture/[videoId].tsx
  pages/lecture/evaluation.tsx
  pages/login.tsx
  pages/oauth/callback/kakao.js
  pages/oauth/callback/kakao.jsx
  pages/register.tsx
  store/comment.ts
  store/lecture.ts
  store/user.ts
  styles/globals.css
  styles/globals.scss
  utils/cookie.ts
Labels: feat

#30 [feature] QR 출석 체크 기능 구현
  components/layout/header/Header.tsx
  components/layout/header/LoginContent.tsx
  components/layout/header/QRCheckInButton.tsx
  store/user.ts
Labels: feat

#31 [deploy] v1.1.0 QR 출석 기능 추가
  components/layout/header/Header.tsx
  components/layout/header/LoginContent.tsx
  components/layout/header/QRCheckInButton.tsx
  store/user.ts
Labels: feat

#34 [feature] 랜딩페이지 챗봇 기능 구현
  .eslintrc.json
  chatbot/ActionProvider.jsx
  chatbot/ChatMessage.jsx
  chatbot/ChatbotHeader.jsx
  chatbot/MessageParser.jsx
  chatbot/config.js
  components/layout/Carousel.jsx
  components/layout/Course.jsx
  components/layout/FixedSection.jsx
  components/layout/Footer.jsx
  components/layout/Slider.jsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/index.tsx
  styles/chatbot.scss
  yarn.lock
Labels: feat

#35 [deploy] v1.1.1 배포
  .eslintrc.json
  chatbot/ActionProvider.jsx
  chatbot/ChatMessage.jsx
  chatbot/ChatbotHeader.jsx
  chatbot/MessageParser.jsx
  chatbot/config.js
  components/layout/Carousel.jsx
  components/layout/Course.jsx
  components/layout/FixedSection.jsx
  components/layout/Footer.jsx
  components/layout/Slider.jsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/index.tsx
  styles/chatbot.scss
  yarn.lock
Labels: feat

#36 [feature] 배포 후 버그 수정
  components/dashboard/dashboardMission/DashboardMission.tsx
  components/layout/header/QRCheckInButton.tsx
  components/lecture/LectureContent.tsx
  components/lecture/LectureQnA.tsx
  components/lecture/evaluation/EvaluationResult.tsx
  components/userBadge/UserBadgeIndicator.tsx
  components/userBadge/modal/DeleteModal.tsx
  components/userBadge/modal/EditModal.tsx
  hooks/useFetch.ts
  pages/_app.tsx
  pages/lecture/evaluation.tsx
  public/images/favicon.ico
Labels: bug, feat

#38 [feature] 배포 후 버그 수정
  components/dashboard/dashboardMission/DashboardMission.tsx
  components/layout/header/QRCheckInButton.tsx
  components/lecture/LectureContent.tsx
  components/lecture/LectureQnA.tsx
  components/lecture/evaluation/EvaluationResult.tsx
  components/userBadge/UserBadgeIndicator.tsx
  components/userBadge/modal/DeleteModal.tsx
  components/userBadge/modal/EditModal.tsx
  hooks/useFetch.ts
  pages/_app.tsx
  pages/lecture/evaluation.tsx
  public/images/favicon.ico
Labels: bug

#40 [deploy] v1.2.1 배포
  hooks/useAuth.ts
  pages/api/axios.ts
  pages/oauth/callback/kakao.jsx
Labels: feat

#41 [deploy] v.1.3.1 배포
  pages/api/axios.ts
Labels: bug

#42 [deploy] v1.4.1 배포
  chatbot/MessageParser.jsx
  components/layout/FixedSection.jsx
  hooks/useAuth.ts
  mocks/data/Comments.ts
  mocks/handler/dashboard/dashboard.ts
  mocks/handler/other.ts
  pages/api/axios.ts
  pages/api/other.ts
  pages/oauth/callback/kakao.jsx
  public/fonts/Pretendard-Bold.woff2
  public/fonts/Pretendard-Medium.woff2
  public/fonts/Pretendard-Regular.woff2
  styles/globals.scss
Labels: bug, feat

#43 [deploy] v1.4.2 배포
  components/layout/BaseLayout.tsx
  components/layout/header/Header.tsx
  mocks/handler/auth.ts
  pages/_app.tsx
  pages/oauth/callback/kakao.jsx
Labels: bug

#44 [deploy] v1.4.3 배포
  pages/api/axios.ts
Labels: bug

#45 [deploy] v1.4.4 배포
  components/dashboard/dashboardMission/MissionUpload.tsx
Labels: bug

#46 [deploy] v1.4.5 배포
  pages/api/axios.ts
Labels: bug

#48 [deploy] v1.4.7 배포
  components/lecture/LectureContent.tsx
Labels: bug

#49 [deploy] v1.4.8 배포
  components/layout/BaseLayout.tsx
Labels: bug

#50 [deploy] v1.4.9 배포
  components/layout/FixedSection.jsx
  components/layout/header/Header.tsx
Labels: bug
